export function exportDataJs(data, { includeDeathPositions = true } = {}) {
  const payload = includeDeathPositions ? data : stripDeathPositions(data);
  const json = JSON.stringify(payload, null, 2);
  return `// Generated by BISWCL admin at ${new Date().toISOString()}\nwindow.WCL_DASHBOARD_DATA = ${json};\n`;
}

function stripDeathPositions(data) {
  return {
    ...data,
    bosses: (data.bosses || []).map((boss) => ({
      ...boss,
      reports: (boss.reports || []).map((report) => ({
        ...report,
        pulls: (report.pulls || []).map((pull) => ({ ...pull, deathPositions: [] }))
      }))
    }))
  };
}
